config/routes.rb
Rover::Application.routes.draw do
  match '/login' => "user_sessions#new"
  match '/logout' => "user_sessions#destroy"
  match 'signup' => 'users#new', :as => :signup

  resources :solutions, :only => :create
  resources :users, :only => :create
  resources :user_sessions
  resources :levels

  root :to => 'levels#index'

end

app/models/level.rb
class Level < ActiveRecord::Base
  attr_accessible :name, :position
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  attr_accessible :level

  belongs_to :user
  belongs_to :level
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :solutions
  has_many :solved_levels, :through => :solutions, :source => :level

  acts_as_authentic do |c|
    c.require_password_confirmation = false
  end

  def current_level
    if solved_levels.any?
      Level.where("id NOT IN (?)", solved_levels).order(:position).first
    else
      Level.first
    end
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user_session, :current_user

  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def require_user
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to login_path
      return false
    end
    true
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

  def show_welcome_page_if_not_logged_in
    unless current_user
      render :template => "welcome/index", :layout => 'welcome'
    end
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_filter :show_welcome_page_if_not_logged_in, :only => :index
  before_filter :require_user

  def index
    respond_to do |format|
      format.json do
        render :json => current_user.current_level.to_json(:only => [:name, :position])
      end
      format.html
    end
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_filter :require_user

  def create
    level = Level.where(:position => params[:position]).first
    solution = current_user.solutions.build(:level => level)
    solution.save!
    respond_to do |format|
      format.json do
        render :json => solution.to_json(:only => :id)
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  layout 'login'

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    if @user_session.save
      redirect_back_or_default root_path
    else
      render :action => :new
    end
  end

  def destroy
    if current_user_session
      current_user_session.destroy
    end
    flash[:notice] = "See you next time!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'login'

  def new
    @user = User.new
  end

  def create
    result = Builders::UserBuilder.new(params[:user]).build
    if result.success
      redirect_to root_path
    else
      @user = result.object
      render :action => :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_class(f, attribute)
    'error' unless f.error_message_on(attribute).blank?
  end

  def inline_error_message(f, attribute)
    if f.error_message_on :email
      content_tag :span, :class => 'help-inline' do
        f.error_message_on attribute
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>RoverGame</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Explore the universe">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>

    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!--
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
    -->
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'RoverGame', root_path, :class => 'brand' %>
          <% if current_user %>
            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#"
                  class="dropdown-toggle"
                  data-toggle="dropdown">
                  <%= current_user.name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Log out", logout_path %></li>
                </ul>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <% if message = flash[:notice] %>
        <div class="alert alert-info">
          <a class="close" data-dismiss="alert">×</a>
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
    <%= yield :jquery %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Continue a RoverGame</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>

    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
    <%= yield :jquery %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>RoverGame</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>

    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <h3 class="muted">RoverGame</h3>
      </div>

      <hr>

      <div class="jumbotron">
        <h1>Welcome to RoverGame!</h1>
        <p class="lead">Program a rover from the ground up for autonomous exploration of Mars!</p>
        <%= link_to 'New Game', signup_path, :class => 'btn btn-large btn-success' %>
        <%= link_to 'Continue', login_path, :class => 'btn btn-large btn-info' %>
      </div>

      <hr>

      <div class="footer">
        <p>&copy; Jeff Talbot 2012</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :jquery %>
  </body>
</html>

app/views/levels/index.html.erb
<div class="row">
  <div class="span-main offset-side">
    <div id="info" class="pull-right">
      Heading <span id="heading" class="label label-info"></span>
    </div>
    <span id="status" class="label">Stopped</span>
  </div>
</div>
<div class="clearfix" style="margin-top: 4px"></div>
<div class="row">
  <div id="program-panel" class="span-side">
  </div>
  <div class="span-main">
    <div id="level-content">
    </div>
  </div>
</div>
<div class="row">
  <div class="span-side">
    <div class="btn-toolbar">
      <button id="run-program" class="btn"><i class="icon-play"></i> Run</button>
      <button id="pause-program" class="btn"><i class="icon-pause"></i> Pause</button>
      <button id="stop-program" class="btn"><i class="icon-repeat"></i> <span>Generate</span></button>
    </div>
  </div>
  <div id="view-mission" class="span-main">
    <div class="btn-toolbar">
      <button class="btn pull-right" href="#level-mission" data-toggle="modal"><i class="icon-bookmark"></i> View Mission</button>
    </div>
  </div>
</div>

<div class="modal hide fade" id="level-mission">
  <div class="modal-header">
    <h3>Level <span class="level-number">1</span> Mission</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">OK</a>
  </div>
</div>

<div class="modal hide fade" id="goal-reached">
  <div class="modal-header">
    <h3>Mission Complete!</h3>
  </div>
  <div class="modal-body">
    <p>Congratulations, you completed the mission!</p>
  </div>
  <div class="modal-footer">
    <a id="next-level" href="#" class="btn btn-success">Continue</a>
  </div>
</div>

<% content_for :jquery do %>
  <%= javascript_tag do %>
    <%= render :partial => 'shared/level.js' %>
  <% end %>
<% end %>

app/views/shared/_level.js.erb
$(function() {
  var container = RVR.container({}),
      grid = RVR.grid({
        container: container
      }),

      levelParams,
      level,
      rover,
      goal,

      loadNextLevel = function() {
        $.getJSON('/levels', {}, function(data) {
          levelParams = data;
          level = RVR[levelParams.name]();
          initializeLevel();
        });
      },

      showGoalReached = function() {
        $("#next-level").removeClass("btn-success").addClass("disabled").text("Saving...");
        $("#goal-reached").modal('show');
      },

      showLevelContinue = function() {
        $("#next-level").removeClass("disabled").addClass("btn-success").text("Continue");
      },

      solutionStoreFailed = function(jqXHR, textStatus, errorThrown) {
        alert("There was a problem saving your solution.");
      },

      storeLevelSolution = function() {
        $.ajax({
          type: 'POST',
          url: '/solutions',
          data: {position: levelParams.position},
          dataType: "json",
          success: showLevelContinue,
          error: solutionStoreFailed
        });
      },

      initializeLevel = function() {
        level.grid(grid);
        rover = level.rover();
        goal = level.goal();
        initializeProgramPanel();
        $(".level-number").text(levelParams.position);
        $("#level-mission .modal-body").html("");
        level.mission.forEach(function(paragraph) {
          $("#level-mission .modal-body").append(
            $("<p/>").text(paragraph)
          );
        });
        $("#level-mission").modal("show");
      },

      animatedRender = function() {
        d3.transition()
          .duration(750)
          .each(render);
      },

      render = function() {
        level.render();
        rover.render();
        goal.render();
      },

      timeout,

      updateScene = function() {
        rover.updatePosition();
        rover.render();

        if (!goal.reached(rover.getPosition())) {
          timeout = setTimeout(updateScene, RVR.transitionDuration);
        } else {
          stop();
          showGoalReached();
          storeLevelSolution();
        }
      },

      generate = function() {
        rover.reset();
        level.reset();
        render();
      },

      topLevelInstructions = RVR.instructionGroups.get(),

      addBlock = function(instruction, element, placeholder) {
        var block = $("<div/>", {class: "well block"}),
            linkWrapper = $("<p/>", {class: "add-instruction"});

        if (placeholder) {
          $("<div/>", {class: "placeholder"}).append($("<p/>").text("Otherwise")).insertAfter(element.closest(".instruction-container"));
        }

        block.insertAfter(element.closest(".instruction-container"));

        linkWrapper.appendTo(block);

        $("<a/>", {href: "#", text: "Add Instruction"}).appendTo(linkWrapper);

        addInstructionRow(linkWrapper);

        return block;
      },

      removeBlock = function(instruction, element) {
        var nextRow = element.closest(".instruction-container").next();
        if (nextRow.hasClass("block")) {
          nextRow.remove();
        }
        nextRow = element.closest(".instruction-container").next();
        if (nextRow.hasClass("placeholder")) {
          nextRow.next().remove();
          nextRow.remove();
        }
      },

      addInstructionRow = function(addLink) {
        addInstructionSelect(
          $("<div/>", {class: "instruction-container"}).insertBefore(addLink)
        );
      },

      renderInstruction = function(instruction, container) {
        var input = container.find("input.instruction"),
            showInstructions = $('<i class="icon-circle-arrow-down edit-instruction instruction-control" style="display:none"></i>'),
            deleteInstruction = $('<i class="icon-remove-circle remove-instruction instruction-control" style="display:none"></i>'),
            select2Container = container.find(".select2-container"),
            instructionText,
            argSelect,
            block;

        select2Container.hide();

        if (instruction.args && instruction.args.length > 0) {
          instructionText = $('<p/>');

          instruction.args.forEach(function(argParams) {
            argSelect = $("<select/>", {name: argParams.name, class: "arguments"});
            argParams.values.forEach(function(argValue) {
              argSelect.append($('<option/>', {value: argValue, text: argValue}));
            });

            instructionText.append(
              $('<span/>', {text: argParams.label}).append(argSelect)
            )
          });
        } else {
          instructionText = $('<p/>', {text: instruction.selectLabel || instruction.label});
        }

        if (instruction.block) {
          container.addClass('block-container');
        }

        showInstructions.click(function() {
          showInstructions.closest(".instruction-content").hide();
          select2Container.show();
          input.select2("open");
        });

        deleteInstruction.click(function() {
          container.remove();
        });

        container.append(
          $('<div/>', {class: 'instruction-content'})
            .append(showInstructions)
            .append(deleteInstruction)
            .append(instructionText)
        );

        removeBlock(instruction, input);

        if (typeof instruction.block !== "undefined") {
          block = addBlock(instruction, input);
          if (instruction.value === "if") {
            addBlock(instruction, input, "Otherwise").addClass("primary");
            block.addClass("secondary");
          }
        }
      },

      formatInstructionSelect = function(data, container) {
        renderInstruction(data.instruction, container.closest(".instruction-container"));

        return data.instruction.label; 
      },

      formatInstructionResult = function(data) {
        if (!data.id) return data.text;

        return data.instruction.label; 
      },

      addInstructionSelect = function(parent) {
        var input = $("<input/>", {type: "hidden", class: "instruction", style: "width:100%"}).appendTo(parent),
            data = [],
            children;

        topLevelInstructions.forEach(function(instructionGroup) {
          children = [];

          instructionGroup.instructions.forEach(function(instruction) {
            children.push({id: instruction.value, instruction: instruction});
          });

          data.push({text: instructionGroup.label, children: children});
        });

        input.select2({
          placeholder: "Choose an instruction",
          data: data,
          formatResult: formatInstructionResult,
          formatSelection: formatInstructionSelect
        });
      },

      prepareInstruction = function(instructionElement) {
        var data, instruction, instance, container;

        data = instructionElement.select2("data");
        if (data == null) {
          return null;
        }
        instruction = data.instruction;
        instance = instruction.instance();
        container = instructionElement.closest(".instruction-container");

        container.find("select.arguments").each(function() {
          instance.arg($(this).attr("name"), $(this).val());
        });

        if (instruction.block) {
          container.next().children().not(".block").find("input.instruction").each(function() {
            var instruction = prepareInstruction($(this));
            if (instruction !== null) {
              instance.subInstruction(instruction);
            }
          });
        }

        if (instruction.value === "if") {
          container.next().next().next().children().not(".block").find("input.instruction").each(function() {
            var instruction = prepareInstruction($(this));
            if (instruction !== null) {
              instance.elseInstruction(instruction);
            }
          });
        }

        return instance;
      },

      initializeProgramPanel = function() {
        $("#program-panel").empty()
          .append($("<p/>", {class: "add-instruction"})
            .append($("<a/>", {href: "#"}).text("Add Instruction")))

        addInstructionRow($(".add-instruction"));
        generate();
      },

      stop = function() {
        if (typeof timeout !== "undefined" && timeout != null) {
          clearTimeout(timeout);
          timeout = null;
          $("#status").text("Stopped").removeClass("label-success").removeClass("label-warning");
          $("#stop-program span").text("Generate");
          $("#stop-program i").removeClass("icon-stop").addClass("icon-repeat");
        }
      },

      run = function() {
        $("#status").removeClass("label-warning").addClass("label-success").text("Running");
        $("#stop-program span").text("Stop");
        $("#stop-program i").removeClass("icon-repeat").addClass("icon-stop");
        $("#program-panel > div.instruction-container").each(function() {
          var instruction = prepareInstruction($(this).find("input.instruction"));
          if (instruction != null) {
            instruction.callback(rover);
          }
        });
        timeout = setTimeout(updateScene, RVR.transitionDuration);
      };

    $("#generate").click(function() {
      generate();
    });

    $("#run-program").click(function() {
      stop();
      run();
    });

    $("#pause-program").click(function() {
      $("#status").text("Paused").removeClass("label-success").addClass("label-warning");
      stop();
    });

    $("#stop-program").click(function() {
      stop();
      generate();
    });

    $("#next-level").click(function() {
      $("#goal-reached").modal('hide');
      level.clear();
      loadNextLevel();
      return false;
    });

    $(document).on("click", ".add-instruction a", function() {
      addInstructionRow($(this).closest(".add-instruction"));
      return false;
    });

    $(document).on("mouseenter", ".instruction-container", function() {
      $(this).find(".instruction-control").show();
    });

    $(document).on("mouseleave", ".instruction-container", function() {
      $(this).find(".instruction-control").hide();
    });

    loadNextLevel();
});

app/views/user_sessions/new.html.erb
<%= form_for @user_session, :html => {:class => "form-signin"} do |f| %>
  <% if @user_session.errors.any? %>
    <div class="alert alert-error">
      <strong>Oops.</strong> Your email and password did not match. Please try again.
    </div>
  <% end %>
  <h2 class="form-signin-heading">Please sign in</h2>
  <%= f.text_field :email, :class => "input-block-level", :placeholder => "Email address" %>
  <%= f.password_field :password, :class => "input-block-level", :placeholder => "Password" %>
  <button class="btn btn-large btn-primary" type="submit">Sign in</button>
<% end %>

<% unless @user_session.errors.any? %>
  <% content_for :jquery do %>
    <%= javascript_tag do %>
      $(function() {
        $("#user_session_email").focus();
      });
    <% end %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, :html => {:class => "form-signin"} do |f| %>
  <h2 class="form-signin-heading">Start a New Game</h2>
  <%= f.text_field :name, :class => "input-block-level", :placeholder => "Your name" %>
  <%= f.text_field :email, :class => "input-block-level", :placeholder => "Email address" %>
  <%= f.password_field :password, :class => "input-block-level", :placeholder => "Choose a password" %>
  <button class="btn btn-large btn-primary" type="submit">Start</button>
<% end %>

<% unless @user.errors.any? %>
  <% content_for :jquery do %>
    <%= javascript_tag do %>
      $(function() {
        $("#user_name").focus();
      });
    <% end %>
  <% end %>
<% end %>